### ISSUE TITLE
Detail explanation of Ideas

### ISSUE THREAD

**Issue by harshalgala** [harshalgala/se17-Q#9]
Write your idea along with the paper or literature you get by tonight or maximum tomorrow morning

**Comment by qiufengyu21** [comment]
Automatic Equation Solver
A mobile application which automatically solves the equation entered by the user (The equation doesn't have to be complicated, because even a simple polynomial function can take a lot of time to solve).

User can input the equation in these 3 ways: 
1: Type the equation manually by tapping on the virtual keyboard displayed on the screen
2: Scan the equation. It can be done by using the cell phone camera
3: Voice. User may speak the equation out loud. For example, user can say something like: 3x+5=15, and then the equation will be displayed on the screen, then the user may hit the solve button to solve the equation.
It has been implemented by application [Photomath](https://photomath.net/en/) a part of the project 
------------------------------------------------------------------------------------------
A Chrome or Firefox extension which allows you to quickly close the current tab in 3 different ways:
1: Double left click the tab
2: Mouse gesture (for example, hold the mouse and draw a cross sign on the screen)
3: Still struggling with the third solution...
http://www.distributedworkplace.com/DW/News/2008%20News%20August-December/Google%20Redefines%20Web%20Browser.doc

------------------------------------------------------------------------------------------
A Chrome or Firefox extension, when you have opened too many tabs, 
1: it allows you to preview the tab by hovering your mouse on the tab
2: It allows you to click a button and merge all the tabs into a list.
3: ...

**Comment by harshalgala** [comment]
Grocery Crowd Sourcing
This is an application in which we want to solve the problem of going to a grocery place or a general store (eg. Food Lion, Patel Brothers, or even like Walmart). The reason being if we cause of some reason forget to get some things while on our trip to the store which is quiet at a distance or takes time or even costs money to travel out there (in case of students). In these case this idea of the application will help the person to a very great extent.
So we are proposing the idea that the application will have these ways/methods to be implemented:
-> Notification : In this feature the user going to the Grocery store will send the notification to all the persons who have downloaded this application stating that "I ... am going to Grocery do anyone wants anything". He/She will have an option to help any particular person as well a limit of weight decided by him to carry other than his own goods. This will be done using GPS and in the 1 mile radius of that personnel all the application users will get the notification.

-> Message Board : In this method a feature called message board will be used and the personnel wanting the things (but are not urgent) can post their requirement (for eg: if a person wants gloves from walmart the gloves being just $5 he/she will not prefer to go all the way to walmart as usually the journey costs more also the walmart sending him to his place also cannot ship as presentlly the shipping is over $50 which is allowed.). By this if someone goes to walmart he/she can get the things for the person.

->Direct Messaging via the application : In this the person can directly message out the persons he/she wants and can even browse people around his area to request to get things for him. This method the person being contacted has a full freedom to not connect with them or not talk to them if they are suspicious about them not knowing the person.

The reason why should one use the application a common question even I had Why should I use the application.
- We are planning to make a credit system and the persons downloading the application for the first time will get 10 credits which is in a way euivalent to about $10.
- So if X asks Y to get a packet of Chips which is about $2 in this way 2 credit from X's account will go to Y's account making X to 8 credit and Y to 12 credit. In this way we are attracting people and thereby we are not loosing anything.
- If a person goes out of his credit he has to buy credits this way we can be making money as well as helping people connecting  them as well as saving them a lots of time.
- In this way we can save time, there is no problem to forget about some things if you forget to buy, and its great for busy as well as lazy people.

If you think of any flaws or problems or even anything wrong with the idea please let me know also will be posting the literature as well as the research papers about this in some time.

Professor and Effat as we were not able to meet you both this week so please give your views about our ideas.

Thank You.

**Comment by gosavipooja** [comment]
**Attendance Management System**
- QR Codes in class: We can use dynamic QR Codes to avoid cheating
To elaborate this idea, we can have an iPad or a Tablet kept in the classroom with dynamically changing QR Codes. The concept of dynamically changing QR codes comes into the scenario to avoid cheating. The student while entering the classroom will scan the QR Code and then enter the class. 
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.683.6728&rep=rep1&type=pdf
Harshal
- Using WiFi
http://www.slideshare.net/supersukanta/smart-attendance-management-system-using-android-wifi-technology
Q
- Finger Print Scanner on iPads/Tablets
The iPad/Tablet placed in the classroom will run the application for scanning the fingerprints of the students after the enter the classroom.
http://ibimapublishing.com/articles/JEERBE/2016/813264/
Harshal
-	We can use our student ID Cards for the same however, scanning RFIDs using Android might require some extra efforts.
https://springerplus.springeropen.com/articles/10.1186/2193-1801-3-761
Q
A few more to go..
-	http://www.ijirst.org/articles/IJIRSTV1I1027.pdf
Harshal
-	http://dl.acm.org/citation.cfm?id=2632054
Q
-------------------------------------------------------------------------------------------------------------------

**Meeting Room Booking Application (say for the Hunt library):**
1.	Develop an app that provides you with a similar functionality as the website does however, since mobile applications are better than mobile responsive websites since apps function faster than websites.
2.	Have a QR Code stuck outside every meeting room in Hunt – a quick room booking system.
Third way (yet to be discovered)

**Comment by harshalgala** [comment]
Professor are these ideas feasible please do let us know as well

**Comment by timm** [comment]
sounds like there are more options with Attendance Management System

**Comment by harshalgala** [comment]
We can also use google api for face detection of students also Google's api of random barcode generator which can be scanned by student's phone

**Comment by gosavipooja** [comment]
Attendance Management System -
1. http://ieeexplore.ieee.org/document/5507528/
Harshal
2. https://pdfs.semanticscholar.org/288f/0459675d41e2d3bbb8b6b65bc927ffe57262.pdf
Q
3. http://ieeexplore.ieee.org/abstract/document/7789812/
Harshal

**Comment by harshalgala** [comment]
Pooja and Q are you able to access the IEEExplore Papers?

**Comment by gosavipooja** [comment]
yes.. Shall I share you a copy of those?

**Comment by harshalgala** [comment]
Just show me how you accessed.

**Comment by gosavipooja** [comment]
Hey.  I guess I was in the library that's why I could access it from the library laptop.. Can't access it from home network though

**Comment by harshalgala** [comment]
Thank you for the pdfs Pooja
